### ISSUE TITLE
域名挂了

### ISSUE THREAD

**Issue by Colinwood11** [g-plane/unofficial-plugins-market#1]
23333

**Comment by g-plane** [comment]
其实原来的服务器是暂时临时借别人的，时间是两个月。现在时间已经过了。
我还在考虑应该放在哪里，不过请放心，我会把数据迁移好的。~可能会跳票~

**Comment by Colinwood11** [comment]
我有服务器，如果你需要的话。。

**Comment by Colinwood11** [comment]
我Q   ■■■■

**Comment by g-plane** [comment]
其实免费空间我也有的，不过制作插件的人实在太少了，专门开个服务器不值得。初步打算放个json文件到GitHub或Git@OSC这样的平台就好了。

**Comment by Colinwood11** [comment]
插件有点思路，但是技术跟不上。没说收你钱啊😳 免费给你用。。。如果不需要的话。。新的源写什么。

**Comment by g-plane** [comment]
并不是收钱什么的，只是觉得如果老是免费地用别人的东西有些过意不去。
如果你愿意提供的话，那我可以把程序和数据发给你。服务器硬件要求不高，之前都是用VPS开的，另外推荐是PHP7。
如果有一天你不想提供服务器了，没关系的，我不介意。不过一定要告诉我，让我备份数据。

**Comment by Colinwood11** [comment]
加我q说吧

**Comment by g-plane** [comment]
感谢！
