### ISSUE TITLE
无法获取插件列表

### ISSUE THREAD

**Issue by dz-paji** [g-plane/unofficial-plugins-market#2]
![image](https://user-images.githubusercontent.com/19299425/27767955-d6950508-5f39-11e7-98c5-a1178eec0d7e.png)
现已确定是最新的插件源。
我的服务器在法国OVH。
不知道是不是特例。
麻烦dalao给看看。

**Comment by g-plane** [comment]
似乎是市场服务器的问题

**Comment by g-plane** [comment]
现在试试看？

**Comment by dz-paji** [comment]
因为nyaboom的原因，我的机子暂时没法启动。等好了我去试试…谢谢了XD



在 2017年7月2日，下午5:12，Pig Fang <notifications@github.com<mailto:notifications@github.com>> 写道：


现在试试看？
