### ISSUE TITLE
打开市场后无反映，等待一定时间后弹窗报错

### ISSUE THREAD

**Issue by Lostpart** [g-plane/unofficial-plugins-market#5]
作者你好，打开市场后一直处于“加载中…”等待足够久的话会弹窗提示下述错误
DataTables warning: table id=plugin-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by g-plane** [comment]
有可能是第三方库的问题，下个版本考虑解决。

**Comment by g-plane** [comment]
Fixed in ccd0e1780dfba9366a6ec955566857a469eb9f2e
