### ISSUE TITLE
第三方插件市场源

### ISSUE THREAD

**Issue by tnqzh123** [g-plane/unofficial-plugins-market#6]
貌似最近很多插件都没有更新到默认插件市场源？
我嫌一个个手动下载解压上传更新太麻烦了，就自己写了个源，地址是：
```
https://www.littleqiu.net/bs/plugins.json
```
源内所有插件的下载均来源于 Coding 上的 [bs-plugins-archive 仓库](https://coding.net/u/printempw/p/bs-plugins-archive/git)。需要注意的是这个源**只收录了部分插件**（当前为 16 个，未来视我的需求等因素可能会收录更多），如果需要安装未被收录的插件，仍需要手动下载解压上传安装。
这个源会不定期更新（而不是与插件同时更新）。

**Comment by g-plane** [comment]
BS 本身可能会带有插件市场功能。如果实现了的话，这个插件也就没有存在的必要了。
事实上您可以直接更新 https://github.com/bs-community/plugins-market-data 内的数据（您有写入权限）。

**Comment by tnqzh123** [comment]
目前我没有在 BS 的最新开发版中发现有自带插件市场功能。以 BS 当前的更新频率来看，自带的插件市场可能不会在短时间内实现（以上仅为我个人的见解）。
至于直接更新 [plugins-market-data 仓库](https://github.com/bs-community/plugins-market-data)什么的，我觉得有些不妥（毕竟我不是插件开发者）。而且如果报道上出现了什么偏差，我也负不起责任。

**Comment by g-plane** [comment]
> 我觉得有些不妥

其实问题也不大，毕竟只是把版本跟上而已。不过您维护您自己的源，那也是可以的。
